"""add_character_tags

Revision ID: 07ddf4579b79
Revises: 108c0c065124
Create Date: 2026-07-07 11:52:40.912252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07ddf4579b79'
down_revision: Union[str, Sequence[str], None] = '108c0c065124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'tags')
    # ### end Alembic commands ###
