"""remove_hidden_stats

Revision ID: 108c0c065124
Revises: c3f81a90d421
Create Date: 2026-07-07 11:00:04.233408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '108c0c065124'
down_revision: Union[str, Sequence[str], None] = 'c3f81a90d421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'hubris')
    op.drop_column('character', 'empathy')
    op.drop_column('character', 'avarice')
    op.drop_column('character', 'composure')
    op.drop_column('character', 'metabolism')
    op.drop_column('character', 'neuroticism')
    op.drop_column('character', 'exam_readiness')
    op.drop_column('npc', 'loyalty')
    op.drop_column('npc', 'strictness')
    op.drop_column('npc', 'empathy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npc', sa.Column('empathy', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('npc', sa.Column('strictness', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('npc', sa.Column('loyalty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('exam_readiness', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('neuroticism', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('metabolism', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('composure', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('avarice', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('empathy', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('hubris', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
