"""init_database

Revision ID: 182475d85d39
Revises: 
Create Date: 2026-04-06 09:46:51.357240

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182475d85d39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active_character_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('character',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('NEWBORN', 'CHILDHOOD', 'HIGH_SCHOOL', 'COLLEGE', 'ADULT', 'ELDER', name='stage'), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=False),
    sa.Column('mind', sa.Integer(), nullable=False),
    sa.Column('joy', sa.Integer(), nullable=False),
    sa.Column('appeal', sa.Integer(), nullable=False),
    sa.Column('savvy', sa.Integer(), nullable=False),
    sa.Column('composure', sa.Integer(), nullable=False),
    sa.Column('neuroticism', sa.Integer(), nullable=False),
    sa.Column('sexuality', sa.Enum('STRAIGHT', 'GAY', 'BISEXUAL', 'ASEXUAL', 'QUESTIONING', name='sexuality'), nullable=False),
    sa.Column('fertility', sa.Integer(), nullable=False),
    sa.Column('immunity', sa.Integer(), nullable=False),
    sa.Column('metabolism', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.Integer(), nullable=False),
    sa.Column('empathy', sa.Integer(), nullable=False),
    sa.Column('sociability', sa.Integer(), nullable=False),
    sa.Column('karma', sa.Integer(), nullable=False),
    sa.Column('hubris', sa.Integer(), nullable=False),
    sa.Column('avarice', sa.Integer(), nullable=False),
    sa.Column('echoes', sa.JSON(), nullable=True),
    sa.Column('contextual', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_user_id'), 'character', ['user_id'], unique=False)
    op.create_table('lifeevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('char_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifeevent_char_id'), 'lifeevent', ['char_id'], unique=False)
    op.create_table('npc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('char_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('empathy', sa.Integer(), nullable=False),
    sa.Column('temperament', sa.Integer(), nullable=False),
    sa.Column('strictness', sa.Integer(), nullable=False),
    sa.Column('loyalty', sa.Integer(), nullable=False),
    sa.Column('affection', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('respect', sa.Integer(), nullable=False),
    sa.Column('resentment', sa.Integer(), nullable=False),
    sa.Column('is_significant', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_char_id'), 'npc', ['char_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npc_char_id'), table_name='npc')
    op.drop_table('npc')
    op.drop_index(op.f('ix_lifeevent_char_id'), table_name='lifeevent')
    op.drop_table('lifeevent')
    op.drop_index(op.f('ix_character_user_id'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
