"""add_avatar_dna

Revision ID: 324224bf3238
Revises: ae6d5246b0bb
Create Date: 2026-05-25 12:18:32.788772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '324224bf3238'
down_revision: Union[str, Sequence[str], None] = 'ae6d5246b0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('avatar_dna', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'avatar_dna')
    # ### end Alembic commands ###
