"""add avatar_url

Revision ID: 75f96a735ce2
Revises: 35c2cdc63674
Create Date: 2026-07-18 19:47:22.097363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75f96a735ce2'
down_revision: Union[str, Sequence[str], None] = '35c2cdc63674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('character', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'avatar_url')
    op.create_table('debt',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('STUDENT_LOAN', 'CREDIT_CARD', 'FAMILY_LOAN', 'PERSONAL_LOAN', name='debttype'), autoincrement=False, nullable=False),
    sa.Column('principal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remaining_balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('debt_character_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('debt_pkey'))
    )
    op.create_index(op.f('ix_debt_character_id'), 'debt', ['character_id'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('HOUSE', 'VEHICLE', 'JEWELRY', 'ELECTRONICS', name='assettype'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('asset_character_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_pkey'))
    )
    op.create_index(op.f('ix_asset_character_id'), 'asset', ['character_id'], unique=False)
    op.create_table('investment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('GOLD', 'FIXED_DEPOSIT', 'STOCK', 'MUTUAL_FUND', 'CRYPTO', name='investmenttype'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchased_at_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('investment_character_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investment_pkey'))
    )
    op.create_index(op.f('ix_investment_character_id'), 'investment', ['character_id'], unique=False)
    # ### end Alembic commands ###
