"""Added relation_label to npc model

Revision ID: ae6d5246b0bb
Revises: 182475d85d39
Create Date: 2026-04-06 09:51:13.604681

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6d5246b0bb'
down_revision: Union[str, Sequence[str], None] = '182475d85d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npc', sa.Column('relation_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npc', 'relation_label')
    # ### end Alembic commands ###
