"""add_marital_status_to_character

Revision ID: b1202a1f5a1f
Revises: 07ddf4579b79
Create Date: 2026-07-16 12:15:16.465445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1202a1f5a1f'
down_revision: Union[str, Sequence[str], None] = '07ddf4579b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('marital_status', sa.Enum('Single', 'In a Relationship', 'Married', 'Divorced', 'Widowed', name='maritalstatus'), nullable=False, server_default='Single'))
    op.drop_column('character', 'avatar_dna')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('avatar_dna', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('character', 'marital_status')
    # ### end Alembic commands ###
